# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "590c63b95c2f9d614101d3bd0ce4f071"
name = "migration-app"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_content,write_customers,write_orders,read_metaobject_definitions,write_metaobject_definitions,read_files,write_files"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
